
class InputButtons:
    BTN_1 = b'BTN_1'
    BTN_2 = b'BTN_2'
    BTN_3 = b'BTN_3'
    BTN_4 = b'BTN_4'
    BTN_5 = b'BTN_5'
    BTN_6 = b'BTN_6'
    BTN_7 = b'BTN_7'
    BTN_8 = b'BTN_8'
    BTN_9 = b'BTN_9'
    BTN_0 = b'BTN_0'
    BTN_STAR = b'BTN_STAR'
    BTN_SHARP = b'BTN_SHARP'
    BTN_OK = b'BTN_OK'
    BTN_UP = b'BTN_UP'
    BTN_DOWN = b'BTN_DOWN'
    BTN_LEFT = b'BTN_LEFT'
    BTN_RIGHT = b'BTN_RIGHT'
